name: seg-auto
channels:
  - conda-forge
dependencies:
  - absl-py=2.3.1
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - alembic=1.16.5
  - annotated-types=0.7.0
  - anyio=4.11.0
  - aom=3.9.1
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.5
  - attrs=25.3.0
  - aws-c-auth=0.8.6
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.0
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.4
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - bcrypt=5.0.0
  - beautifulsoup4=4.13.5
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=2.0.0
  - charset-normalizer=3.4.3
  - click=8.3.0
  - cloudpickle=3.1.1
  - comm=0.2.3
  - contourpy=1.3.3
  - cryptography=45.0.7
  - cycler=0.12.1
  - databricks-sdk=0.67.0
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - dnspython=2.8.0
  - docker-py=7.1.0
  - email-validator=2.3.0
  - email_validator=2.3.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fastapi=0.118.0
  - fastapi-cli=0.0.13
  - fastapi-core=0.118.0
  - ffmpeg=7.1.1
  - flask=3.1.2
  - flatbuffers=24.12.23
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.0
  - fqdn=1.5.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - frozenlist=1.7.0
  - gast=0.6.0
  - gdk-pixbuf=2.44.2
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glog=0.7.1
  - gmp=6.3.0
  - google-auth=2.40.3
  - google-pasta=0.2.0
  - graphene=3.4.3
  - graphite2=1.3.14
  - graphql-core=3.2.6
  - graphql-relay=3.2.0
  - greenlet=3.2.4
  - grpcio=1.67.1
  - gunicorn=23.0.0
  - h11=0.16.0
  - h2=4.3.0
  - h5py=3.13.0
  - harfbuzz=11.5.1
  - hdf5=1.14.3
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imath=3.1.12
  - importlib-metadata=8.7.0
  - invoke=2.2.0
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jasper=4.2.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keras=3.11.2
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lark=1.3.0
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libasprintf=0.25.1
  - libass=0.17.3
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libcxx=21.1.2
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgettextpo=0.25.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.86.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.67.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libml_dtypes-headers=0.5.3
  - libnghttp2=1.67.0
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopencv=4.11.0
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libopenvino=2025.0.0
  - libopenvino-arm-cpu-plugin=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.5.2
  - libparquet=19.0.1
  - libpng=1.6.50
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libtensorflow_cc=2.18.0
  - libtensorflow_framework=2.18.0
  - libthrift=0.21.0
  - libtiff=4.7.1
  - libusb=1.0.29
  - libutf8proc=2.10.0
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=21.1.0
  - lz4-c=1.10.0
  - mako=1.3.10
  - markdown=3.9
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mistune=3.1.4
  - ml_dtypes=0.4.0
  - mlflow=3.2.0
  - mlflow-skinny=3.2.0
  - mlflow-ui=3.2.0
  - multidict=6.6.3
  - munkres=1.1.4
  - namex=0.1.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - notebook-shim=0.2.4
  - numpy=2.3.3
  - opencv=4.11.0
  - openexr=3.3.5
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.5.3
  - opentelemetry-api=1.37.0
  - opentelemetry-sdk=1.37.0
  - opentelemetry-semantic-conventions=0.58b0
  - opt_einsum=3.4.0
  - optree=0.17.0
  - orc=2.1.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.2
  - pandocfilters=1.5.0
  - pango=1.56.4
  - paramiko=4.0.0
  - parso=0.8.5
  - patsy=1.0.1
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.4.0
  - prometheus-cpp=1.3.0
  - prometheus_client=0.23.1
  - prometheus_flask_exporter=0.23.2
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - protobuf=5.28.3
  - psutil=7.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pure_eval=0.2.3
  - py-opencv=4.11.0
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pydantic=2.11.9
  - pydantic-core=2.33.2
  - pygments=2.19.2
  - pynacl=1.6.0
  - pyobjc-core=11.1
  - pyobjc-framework-cocoa=11.1
  - pyopenssl=25.1.0
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-fastjsonschema=2.21.2
  - python-flatbuffers=25.9.23
  - python-json-logger=2.0.7
  - python-multipart=0.0.20
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyu2f=0.1.5
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - querystring_parser=1.2.4
  - rav1e=0.7.1
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.1.0
  - rich-toolkit=0.15.1
  - rpds-py=0.27.1
  - rsa=4.9.1
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - sdl2=2.32.56
  - sdl3=3.2.22
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8
  - sqlalchemy=2.0.43
  - sqlparse=0.5.3
  - stack_data=0.6.3
  - starlette=0.48.0
  - statsmodels=0.14.5
  - svt-av1=3.0.2
  - tbb=2022.2.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=3.1.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.2
  - traitlets=5.14.3
  - typer=0.19.2
  - typer-slim=0.19.2
  - typer-slim-standard=0.19.2
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.15.0
  - typing-inspection=0.4.1
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - uvicorn=0.37.0
  - uvicorn-standard=0.37.0
  - uvloop=0.21.0
  - watchfiles=1.1.0
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=15.0.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.3
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - altair==5.5.0
      - narwhals==2.5.0
      - pydeck==0.9.1
      - simsimd==6.5.3
      - streamlit==1.50.0
      - stringzilla==4.0.14
      - tenacity==9.1.2
      - toml==0.10.2
